build:
  version: 3.0

accounts:
  message: "welcome back, you are reading from accounts prod file"
  contactDetails:
    name: "Achin Prakash"
    email: "achin.prakash8@gmail.com"
  onCallSupport:
    - "(0631) 250251"
    - "(0631) 450851"