build:
  version: 1.0

accounts:
  message: "welcome back, you are reading from accounts default file"
  contactDetails:
    name: "Achin Prakash"
    email: "achin.pd3@gmail.com"
  onCallSupport:
    - "(0631) 250251"
    - "(0631) 450851"


