server:
  port: 8070


eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false # by default it is true. I don't want to fetch the registry details of other microservice.
    registerWithEureka: false # Don't register with yourself. Don't expose your details in the registry of the service discovery.
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/