build:
  version: 3.0

loans:
  message: "welcome back, you are reading from loans production file"
  contactDetails:
    name: "Achin Prakash"
    email: "achin.pd3@gmail.com"
  onCallSupport:
    - "(0631) 250251"
    - "(0631) 450851"