build:
  version: 3.0

loans:
  message: "welcome back, you are reading from loans prod file"
  contactDetails:
    name: "Achin Prakash"
    email: "achin.pd4@gmail.com"
  onCallSupport:
    - "(0631) 250251"
    - "(0631) 450851"